apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-pv-volume
  labels:
    type: local
    app: teamcity-server
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/teamcity-data"
