apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-pv-volume
  labels:
    app: teamcity-server
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/hipr/teamcity-data
