server:
  image: jetbrains/teamcity-server
  tag: latest
  replicas: 1

  pvc:
    existingVolume: teamcity-pv-volume
    storageClass: standard
    accessMode: ReadWriteMany
    size: 10Gi

  ingress:
    enabled: true
    host: teamcity.hipr.k8s
    path: /
    className: nginx
    annotations: { }

resources: { }

postgresql:
  enabled: true
  database: teamcity
  username: teamcity
  password: securepassword
  storage: 5Gi
