server:
  image: jetbrains/teamcity-server
  tag: latest
  replicas: 1

  pvc:
    existingVolume: teamcity-pv-volume
    storageClass: standard
    accessMode: ReadWriteMany
    size: 10Gi

  ingress:
    enabled: true
    host: teamcity.hipr.k8s
    path: /
    className: nginx
    annotations: { }

agent:
  image: jetbrains/teamcity-agent
  tag: latest
  replicas: 1
  serverUrl: http://teamcity
  autoRegister:
    enabled: true
    authToken: "my-auth-token"
    agentNamePrefix: "docker-enabled-agent"

dockerSocketPath: /var/run/docker-kube.sock

env:
  - name: DOCKER_HOST
    value: unix:///var/run/docker-kube.sock

resources: { }

postgresql:
  enabled: true
  database: teamcity
  username: teamcity
  password: securepassword
  storage: 5Gi
