apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity-postgresql
  template:
    metadata:
      labels:
        app: teamcity-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: teamcity-postgres-secret
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: teamcity-postgres-pvc
