apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-server
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: teamcity-server
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      containers:
        - name: teamcity-server
          image: "{{ .Values.server.image }}:{{ .Values.server.tag }}"
          ports:
            - containerPort: 8111
          volumeMounts:
            - mountPath: /data/teamcity_server/datadir
              name: data
          env:
            - name: TEAMCITY_SERVER_MEM_OPTS
              value: >-
                -Dteamcity.database.type=postgres
                -Dteamcity.database.postgres.server=teamcity-postgresql
                -Dteamcity.database.postgres.port=5432
                -Dteamcity.database.postgres.name={{ .Values.postgresql.database }}
                -Dteamcity.database.postgres.user={{ .Values.postgresql.username }}
                -Dteamcity.database.postgres.password={{ .Values.postgresql.password }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: teamcity-data
