apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-server
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: teamcity-server
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      containers:
        - name: teamcity-server
          image: "{{ .Values.server.image }}:{{ .Values.server.tag }}"
          ports:
            - containerPort: 8111
          volumeMounts:
            - mountPath: /data/teamcity_server/datadir
              name: data
          env:
            - name: POSTGRES_HOST
              value: "teamcity-postgresql"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: teamcity-pvc
